### ISSUE TITLE
Split WORK_SESSION_COUNT to two separate Counters

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#13]
Future functionality will require the app to maintain two separate work session counters: 
1. for displaying the number of tasks completed for a particular task, i.e., this will reset to zero when user enters new task.
2. counter which controls the break cycles, i.e., the one whose value is currently displayed on screen and gets incremented by 1 when a task is completed.

### What is required?
Add one more shared preference similar to the current `WORK_SESSION_COUNT` - let's call it `TASK_ON_HAND_COUNT`.

It should increment every time the previous 'WORK_SESSION_COUNT` incremented.

The `workSessionCountTextView` should now update its value from `TASK_ON_HAND_COUNT`

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
do TASK_ON_HAND_COUNT have any impact on UI of app right now

**Comment by numerative** [comment]
Yes, it will.
The textview that shows number of completed tasks will now fetch data from this new TASK_ON_HAND_COUNT.

Also, when the user changes the task, it'll reset to 0 - but for this, I'll create a separate issue.

**Comment by chanmol1999** [comment]
i mean the text WORK_SESSION_COUNT is displaying same is to be displayed by the new one

**Comment by numerative** [comment]
Correct, but it is okay if the figures are different.

**Comment by numerative** [comment]
> The `workSessionCountTextView` should now update its value from `TASK_ON_HAND_COUNT`
