### ISSUE TITLE
Button press feedback for ✔ and ⚙

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#15]
Button press should provide a visual feedback: _like a ripple effect_.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by rob729** [comment]
@numerative I would like to work on this issue.

**Comment by codersanjeev** [comment]
go ahead @rob729

**Comment by rob729** [comment]
@thedevelopersanjeev I have made a PR for this issue.
Please review it.
