### ISSUE TITLE
Adjustable volume sliders for Ticking and Ringing sounds

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#16]
Add adjustable sliders to control ticking and ringing sounds in the Settings Activity.

The scope of this commit includes both UI and Java Logic changes.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
I am working on this issue.

**Comment by codersanjeev** [comment]
Please work on one issue at one time.

**Comment by chanmol1999** [comment]
Okk understood.If it remains unassigned i work on it later on
