### ISSUE TITLE
Add spinner for long break interval [XML only]

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#17]
Add a spinner in Settings Activity.
Title: _Start Long Break after_
Spinner Values: _2_ , _3_ , _4_ ,  _5_, _6_

Scope of this issue covers only XML changes required.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
I would like to work on this .you need changes in xml file only as much i can infer.

**Comment by numerative** [comment]
That's correct. The XML changes are required in settings activity.
You may work on this issue.
