### ISSUE TITLE
Long Break Interval (Java Logic)

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#18]
> Starts after #17 

Allow users to select when to take a long break.

The default should be 4 intervals, but allow users to take the value from the spinner in Settings Activity. 

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
can you please elaborate more on this

**Comment by numerative** [comment]
Sure.
If you use the app right now, the long break session starts after every 4th work session, i.e. Short break, short break, short break and then a long break.

If you look into the code, you'll find that it is controlled by this code. 

```
if (currentWorkSessionCount % 4 == 0)

            return LONG_BREAK;
```

What we want to achieve is a way for the user to select the number of work sessions until the app allows long break.

We've already setup the spinner in XML. Now based on the selected position, the `4` in the code above must be replaced with the value chosen from that spinner.

Is this clear enough?
