### ISSUE TITLE
Click Task Name to Edit

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#19]
Allow user to edit Task Name when tapped.

### Expected behaviour
- No separate alert dialog should popup on tap.
- Tapping outside the EditText box retains the values on the screen.
- Task Name is retained even after the app is cleared from memory. (SharedPreferences)

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
I would like to work on this issue

**Comment by codersanjeev** [comment]
go ahead @chanmol1999
