### ISSUE TITLE
Orientation Changes: CountdownTextView resets for a split second

### ISSUE THREAD

**Issue by codersanjeev** [NJACKWinterOfCode/android-productivity-timer-tametu-app#2]
When changing orientation, the ContDownTextView resets to start timer minutes for a split second. This doesn't affect the actual countdown timer.

### Steps to reproduce
Change orientation to from portrait to landscape or vice versa.

### Expected behavior
Should retain the value when the orientation changed.

### Actual behavior
e.g. the countdown is at 24:30 but when orientation changes the textview displays 25:00 for a split second before resuming to 24:29.

Interested in taking up this issue? Leave a comment expressing your interest.

**Comment by piedcipher** [comment]
Working on this.

**Comment by numerative** [comment]
Swell!
