### ISSUE TITLE
Rebranding and Refactoring the app's identity

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#21]
**Bad news!**
We can't call this app Pomodoro for copyright issues. 

For this reason, we plan to give this app a new name: **_Tamétû_**

Besides changing the name of the app, it would be a good idea to even change the package name as well.

While even these two steps should be enough, I wish to leave no stone unturned. Therefore, for the scope of this issue, every instance of Pomodoro should be changed to the word Tamétû or Tametu.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
You mean instead of pomodoro everywhere tametu will be written if that i will work on this.

**Comment by codersanjeev** [comment]
go ahead @chanmol1999

**Comment by chanmol1999** [comment]
Again a doubt i have to just rebrand the app or whole of the repository i mean including readme files etc.

**Comment by codersanjeev** [comment]
you just have to change app name and the package name for now... and make sure that apk builds properly after refactoring...
