### ISSUE TITLE
App must support portrait mode only

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/android-productivity-timer-tametu-app#24]
The current UI of the App demands it to be available in portrait mode only.

### Steps to reproduce
change in manifest file.

### Expected behaviour
Must show only in portrait mode as standard apps.

### Actual behaviour
Currently landscape and portrait both exists.

### Would you like to work on the issue?
Yes.

-----------------------------------

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
Assigned!
Since no separate use case for landscape layout has been planned, it would be a good idea to lock the UI in only portrait mode. Waiting for your PR.

Thanks.
