### ISSUE TITLE
Error with saving time settings when changed

### ISSUE THREAD

**Issue by kshitijsuri90** [NJACKWinterOfCode/android-productivity-timer-tametu-app#28]
### Describe your issue here.
When the time for the task is changed to other and the home screen is brought again the time it starts with is with the previous setting.
### Steps to reproduce
Tell us how to reproduce this issue. 
Change time setting and start the timer

### Expected behaviour
Tell us what should happen
Should start with the time specified

### Actual behaviour
Tell us what happens instead
Instead starts from the previous setting
![20181213_021514](https://user-images.githubusercontent.com/34534870/49897973-9fca4300-fe7d-11e8-8d72-fe937563d2d6.gif)

### Would you like to work on the issue?
Tell us if you would like to work on this issue
Yes
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
Whoa! Awesome bug find @kshitijsuri90!
I checked and the same happens even for breaks.

Please do work on this issue. Thanks! :)

**Comment by kshitijsuri90** [comment]
@numerative Any suggestions on how best to go about this?
