### ISSUE TITLE
No need to write Pomodoro in Button as alread in Title

### ISSUE THREAD

**Issue by kshitijsuri90** [NJACKWinterOfCode/android-productivity-timer-tametu-app#29]
### Describe your issue here.
There is no need for Pomodoro text in start and cancel button in app.

### Would you like to work on the issue?
Tell us if you would like to work on this issue
Yes
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
For now let it be. The button actually undertakes various tasks like starting pomdoro, starting breaks and cancelling all running instances and hence it correctly displays the action it is about to perform on click.
