### ISSUE TITLE
Design Layout Mockups for the App (2 screens)

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#3]
The app's working, but that's just it. A well-polished UI is a must if you want your user to love your app. Our app needs UI polish and the first step towards it would be preparing mockups.
Below is the current screen shot of our app.

![pomodoro_screen_1](https://user-images.githubusercontent.com/28054527/48408222-cef67300-e75e-11e8-8f81-5d210ee7db62.png) ![pomodoro_screen_2](https://user-images.githubusercontent.com/28054527/48408224-cef67300-e75e-11e8-9a7f-7f139063ca0c.png)

**REQUIRED:**
1. Mockups of the above two screens. 
2. Mockups must adhere to material guidelines. (e.g. choice of colours, padding, font sizes, etc.)

_Be imaginative, but be grounded... After all it needs to be coded too, right?_

Good Luck!

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by AjaySharvesh3** [comment]
@numerative I didn't get the issue properly. Whether I have to create a UI like the suggested mockup? Right? If Yes, I'll work on that issue.

**Comment by numerative** [comment]
The above is the current state of the app. We require a wireframe / mockup that has the above elements. We're looking to beautify the app.

**Comment by AjaySharvesh3** [comment]
@numerative So the issue is to make the above UI better? That's it?

**Comment by numerative** [comment]
Yes.

**Comment by AjaySharvesh3** [comment]
I'll work on this issue.

**Comment by numerative** [comment]
Thanks!
We're currently looking for inspiration from uplabs and dribble. I'll tag you here when we have selected a design. It'll be easier to adapt from such a design.

**Comment by ghost** [comment]
@numerative  I am ready for help sorry for late please DM me in slack

**Comment by numerative** [comment]
Finalised submissions from @iamhshaikh.

![web_hi_res_512](https://user-images.githubusercontent.com/28054527/50479432-9358f500-09fc-11e9-83ca-eae04dc70bc5.png)
![mainscreen](https://user-images.githubusercontent.com/28054527/50479433-9358f500-09fc-11e9-90d1-854181ee5690.jpg)
