### ISSUE TITLE
A welcome screen

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/android-productivity-timer-tametu-app#38]
just like the official pomodoro app a screen must appear on app startup with text somewhat like "Welcome to Tametu"
or with text which you like to inculcate.

###Would you like to work on this issue?
yes

**Comment by chanmol1999** [comment]
What about this

**Comment by numerative** [comment]
This is very much needed. But it will need to be beautiful.

**Comment by chanmol1999** [comment]
Would you like to suggest some content or example UI layout or should I prepare myself and share screenshot with you

**Comment by numerative** [comment]
Keep this on hold for a while.
By the end of the day we'll finalize a theme for this app so the UI can be updated and based on this new mockup you can create a similar looking welcome screen.

**Comment by ghost** [comment]
@numerative I am also able to help did you finalize layout for pomodoro activities

**Comment by chanmol1999** [comment]
Is the theme of app decided @numerative .

**Comment by numerative** [comment]
@chanmol1999 the theme has been selected. I'll create an issue within a few hours.

**Comment by numerative** [comment]
Hey @chanmol1999 and @iamhshaikh,
Here is the finalised UI theme.

![mainscreen](https://user-images.githubusercontent.com/28054527/50479433-9358f500-09fc-11e9-90d1-854181ee5690.jpg)

**Comment by chanmol1999** [comment]
So I am going to start work on welcome screen according to this UI

**Comment by numerative** [comment]
You may. But will you please send a revised PR for #40 first ?

**Comment by ghost** [comment]
@chanmol1999  first confirm with @numerative which icon are we gonna use for splash screen

**Comment by numerative** [comment]
Most likely it'll not need an icon, but if it is included, then include the new one.

**Comment by chanmol1999** [comment]
Suggest some points @numerative to be added in welcome screen .Currently i am giving it a 3 second timeout.
![screenshot_20181231_175314](https://user-images.githubusercontent.com/42909612/50560301-78042780-0d25-11e9-8879-e14efb26750d.jpg)

**Comment by chanmol1999** [comment]
> Most likely it'll not need an icon, but if it is included, then include the new one.

where is the new icon

**Comment by numerative** [comment]
@iamhshaikh can you please upload the resources for the new logo? Please also include a transparent version as well.

This is turning out to be good @chanmol1999!
I would suggest:
- a duration of 1 second or less. 3 seconds will feel painfully slow.
- Instead of starting from the top, place it in the centre.
- The tagline is 'get more done, faster' - (which I just noticed has been removed from the app name ?!)
- We'll be waiting for the new logo as we can't use the one which has 'pomodoro' written on it.

**Comment by chanmol1999** [comment]
Yes,  of course @iamhshaikh  there are no drawables present for icon in the google drive link provided by you.

**Comment by ghost** [comment]
I am working on it making it beautiful will upload by tonight

**Comment by ghost** [comment]
![tametuxxxhdpi](https://user-images.githubusercontent.com/42109980/50574991-86cc0680-0e19-11e9-87f5-5b96c8eed2f0.png)

**Comment by chanmol1999** [comment]
Ignore that 10mb released ; how is't @numerative 
![screenshot_20190102_155923](https://user-images.githubusercontent.com/42909612/50588356-b32e6400-0ea7-11e9-8f28-b320d8c07029.jpg)

**Comment by numerative** [comment]
Looks cool man! Let me check the commit and I'll let you know!

**Comment by numerative** [comment]
By the way @chanmol1999,
I am having difficulty figuring out how to change the text color that appears on the spinner (not the popup). Since you designed the UI, can you help?

**Comment by numerative** [comment]
Okay I got it... :point_up_2:
