### ISSUE TITLE
Code UI as per the mockups

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#41]
We've finally selected the UI and it is this:
![mainscreen](https://user-images.githubusercontent.com/28054527/50479433-9358f500-09fc-11e9-90d1-854181ee5690.jpg)

### Required
Adapt the current UI as per the mockups. Do note that UI of the `MainActivity` as well as `SettingsActivity`, both will have to be coded.

This is an actual coding task - we don't need anymore mockups, but actual code.

cc: @iamhshaikh

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
No option of work sessions completed in sample.Will it be or not

**Comment by numerative** [comment]
Yes, it is required but it'll be hidden when break sessions are running or the timer is not running. i.e. it'll be visible only when the work session is running.

**Comment by chanmol1999** [comment]
![index](https://user-images.githubusercontent.com/42909612/50483772-42a0c680-0a13-11e9-84e9-ab06dccb424d.jpeg)
![index1](https://user-images.githubusercontent.com/42909612/50483783-4a606b00-0a13-11e9-9481-17347accc24c.jpeg)

According to the things which i could infer i am sharing two screenshots if i'll improve the one you suggest.I was not able to gather images of play so will add them later on

**Comment by chanmol1999** [comment]
@numerative please share your views regarding this and what about that toggle button for start .Do similar i have to search for stop.
and the work session completed will be visible when any session is completed i am changing its visibility


![origi](https://user-images.githubusercontent.com/42909612/50488496-d335d180-0a28-11e9-95b2-239402e09928.jpeg)

**Comment by numerative** [comment]
This is a good attempt. :+1: 

However, all 3 buttons will need to look pretty, especially the main toggle button.

The toggle button should be play and pause symbols. As a result of doing so the user will not be able to tell whether a break or a work session is running. This can be resolved by indicating the running status in the actionbar which currently only displays the app name.

Also the status bar colour must match pinkish hue immediately below it.

The line below the task name too must go away.

**Comment by chanmol1999** [comment]
@numerative is this design you are expecting.....
![finalui](https://user-images.githubusercontent.com/42909612/50508139-93153400-0aa6-11e9-85fa-f22fb6860e88.jpeg)

**Comment by numerative** [comment]
Nope. It must have some consistent look and feel. This looks like a cut and paste job.

**Comment by ghost** [comment]
**Hello guys **
Here is the image what mockup I am also sharing resources which I am exported from Adobe XD so here is a [link](https://drive.google.com/drive/folders/12KOtaXAzxDr-grq_kNi762BVWxWszrzG?usp=sharing)
![](https://user-images.githubusercontent.com/42109980/50524183-5bd07280-0afa-11e9-98af-85470f229ab2.jpg)
cc: @numerative @chanmol1999 and other who are working on UI coding

**Comment by chanmol1999** [comment]
While working on the UI i am already removing the change option so why a different issue

**Comment by ghost** [comment]
We will implement preferences when user click on card view to set task name and we are going to replace number of sessions with check marks

**Comment by numerative** [comment]
@iamhshaikh One little change required. The stop button shouldn't be :record_button: , but :stop_button: .
Meaning it should be a square. This is a record button.
