### ISSUE TITLE
Timer resets to 25 minute, after choosing any type of break

### ISSUE THREAD

**Issue by atm1504** [NJACKWinterOfCode/android-productivity-timer-tametu-app#42]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
The timer should start from the remaining time left before choosing break.

### Actual behaviour
The timer starts from 25 minutes itself.

### Would you like to work on the issue?
Yes

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
I don't understand what the issue is.

**Comment by atm1504** [comment]
When we click session complete (the tick image), we are asked to choose for a break. After we choose any type of break, and ends the break, the time of the app resets to 25 minutes, instead of time left to complete the session.

**Comment by numerative** [comment]
That's actually how it is supposed to work.

The complete button is to be only used when you've finished a task early, I.e. Before the timer ticks 0. Once you complete the session you can take a break and come back to start a new 25 minute session.

**Comment by atm1504** [comment]
Then, there must be a button to pause the timer in between. This would actually help to find the real time taken to complete the task.

**Comment by numerative** [comment]
Pausing allows for distractions.

**Comment by atm1504** [comment]
So, whats the main motto of the app "wether to complete the task within 25 minutes" or  "25 minutes of continue non-destruction work "?

**Comment by codersanjeev** [comment]
https://en.m.wikipedia.org/wiki/Pomodoro_Technique
