### ISSUE TITLE
There is no response on clicking "change" option

### ISSUE THREAD

**Issue by atm1504** [NJACKWinterOfCode/android-productivity-timer-tametu-app#43]
Describe your issue here.

### Steps to reproduce
In the XML file, create a textview for the number.
Add a change function, that would increase the task number by 1, when the change option is clicked.

### Expected behaviour
The name of the task should change

### Actual behaviour
No response

### Would you like to work on the issue?
Yes. But I might take a bit of time to solve it.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
What is required now is only to remove the 'change task' textview.
The current task name can be edited just be clicking on it.

Would you be interested in removing that textview?

**Comment by atm1504** [comment]
Yes, I would

**Comment by numerative** [comment]
Okay. You may start working on this.
