### ISSUE TITLE
Add a button to reset work sessions completed 

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/android-productivity-timer-tametu-app#46]
If a user wants to start work sessions completed from 0 there be a option in settings or a button to reset work sessions completed to 0.

### Steps to reproduce
change in xml and main activity.

### Expected behaviour
An option to reset counter to 0.

### Actual behaviour
no option for a user if he wants to begin from 0.

### Would you like to work on the issue?
Tell us if you would like to work on this issue
yes
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
Instead of a button, when the user changes the task name, it should reset to 0.

Would you be interested in taking this up?

**Comment by chanmol1999** [comment]
Yes

**Comment by numerative** [comment]
Okay. Please start working on this.
