### ISSUE TITLE
Add a textview to display the time taken to complete the last task

### ISSUE THREAD

**Issue by atm1504** [NJACKWinterOfCode/android-productivity-timer-tametu-app#48]
Describe your issue here.

### Steps to reproduce
>Create a textview in the XML file
>Display the time left in the textview, when the pomodoro ends

### Expected behaviour
There should be a display to show the time taken to complete the last task

### Actual behaviour
There is no display about the time taken to complete the last task

### Would you like to work on the issue?
Yes

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
If ever this feature is introduced, it will be by the way of showing it as a statistics and it will be displayed on a different screen.
Since the main screen is supposed to be clean-looking it'll avoid anything that doesn't fulfil the app's feature.
