### ISSUE TITLE
Main timer button doesn't change when app is used from notifications

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#49]
When either a _Session, Short break or Long break_ is started from the notification, the button state of the main button doesn't change.

### Steps to reproduce
Start any of the above 3 functions from the notifications.

### Expected behaviour
The button state should change to either 'Cancel Tametu' or 'Skip Short/Long Break'

### Actual behaviour
Button doesn't change state.

### Would you like to work on the issue?
Up for grabs for anyone willing to take it up.

cc: @amartya-mondal

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by atm1504** [comment]
I would work on this

**Comment by numerative** [comment]
Okay. Please starting working on this

**Comment by atm1504** [comment]
Can you please explain how to proceed to solve this issue?
