### ISSUE TITLE
Two works running simultaneously

### ISSUE THREAD

**Issue by atm1504** [NJACKWinterOfCode/android-productivity-timer-tametu-app#51]
Describe your issue here.

### Steps to reproduce
Change the button to "Cancel Pomodoro"

### Expected behaviour
As soon as we start a task from notification bar, the "Start Pomodoro" button should change to "Cancel
![defect](https://user-images.githubusercontent.com/43731599/50538891-482a1800-0b9d-11e9-8c84-4e5c95717b0b.gif)
 Pomodoro".

### Actual behaviour
If we start a task from the notification bar, then also we are allowed to start another task simultaneously from the main app 

### Would you like to work on the issue?
Tell us if you would like to work on this issue

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
This is connected to #49
