### ISSUE TITLE
If we start a task from notification bar, it cannot be stopped from the main app

### ISSUE THREAD

**Issue by atm1504** [NJACKWinterOfCode/android-productivity-timer-tametu-app#53]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
We should be able to complete/stop the service from both the main app and the notification bar, depending on the user.

### Actual behaviour
The task now can be stopped only from the notification bar.

### Would you like to work on the issue?
Tell us if you would like to work on this issue

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
This is also connected to #49
