### ISSUE TITLE
Notification Action Buttons: When Break is Complete. 4/4

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#8]
### Required:
Notification which allows users to do undertake following task _when_  the break is complete:

▶ Start Pomodoro

> This issue is in pursuance of #4    

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by 27vinayvyas** [comment]
@numerative  i wish to work on this but i m facing a problem in finding the part of code called when the break finishes. Also in th notification code(it is written two times and i could not  find the diff bw the two)
Thnx if u could help

**Comment by numerative** [comment]
The break and session are both run from countdownservice.

It is just the value of `currentlyRunningServiceType` that determines the outcome when Timer finishes.

**Comment by numerative** [comment]
Also, can you point me to the notification code written two times?

**Comment by 27vinayvyas** [comment]
Its in the mainActivity and in the countDownTimerService Class 
I dont know but i think its the same code

**Comment by numerative** [comment]
```
/**
 * Creates structure for a notification which is shown when a task is Completed.
 * Task can be POMODORO, SHORT_BREAK, LONG_BREAK
 *
 * @return notification.
 */
```

The above notification in the MainActivity is displayed when the timer has finished running.

Whereas the notification is the countdowntimerservice is displayed while the timer is running as a foreground service.

**Comment by numerative** [comment]
Hey @27vinayvyas,
In case if you still wished to clarify any doubts, head over to the gitter room at https://gitter.im/android-productivity-timer-tametu-app/tametu.
